### ISSUE TITLE
Is there a bug in visitors/exatn/GateFactory.hpp CZBody?

### ISSUE THREAD

**Issue by simon-ty** [ORNL-QCI/tnqvm#101]
https://github.com/ORNL-QCI/tnqvm/blob/dc43d69a94ab9e7a3d0af10b733fbf1a69dd09e3/tnqvm/visitors/exatn/GateFactory.hpp#L115

Looking at the definition for CZBody...it looks like a duplicate of CNBody at L108.

**Comment by tnguyen-ornl** [comment]
Hi @simon-ty 

GateFactory.hpp/.cpp are legacy and unused. Gate matrices are defined in the file: https://github.com/ORNL-QCI/tnqvm/blob/master/tnqvm/base/Gates.hpp 

Upon auditing the file, I figured out that some gates were not defined (should be asserting in debug build) and have added them accordingly.
Please let me know if you have any questions.

**Comment by simon-ty** [comment]
Ok thanks for this!  I will test out the fixes shortly.
