### ISSUE TITLE
XACC/TN-QVM Dry Run feature

### ISSUE THREAD

**Issue by DmitryLyakh** [ORNL-QCI/tnqvm#41]
We need to introduce the Dry Run feature in XACC/TN-QVM. I believe Thien has already done this in TN-QVM for the direct quantum circuit contraction. The goal is to be able to get the Flop count for a given quantum circuit without actually running it. So, we need to connect XACC to this new TN-QVM feature to allow XACC users to specify the DryRun option instead of the actual run. Alex, what would the best solution be on the XACC side? DryRun is a property of Accelerator, so we need to be able to modify the Accelerator behavior between ActualRun and DryRun (classical resource estimate only).

**Comment by amccaskey** [comment]
@tnguyen-ornl isn't this basically already done in your latest PR? Should just be a getAccelerator call with appropriate input heterogeneous map

**Comment by amccaskey** [comment]
Should be this right? https://github.com/tnguyen-ornl/tnqvm/blob/tnguyen%2Fsycamore/examples/sycamore/sycamore_circ_contract_flops.cpp#L44

**Comment by tnguyen-ornl** [comment]
Yea, this feature was implemented in the latest pending PR. We added a special boolean key `calc-contract-cost-flops` to ask for a 'dry-run'.

**Comment by DmitryLyakh** [comment]
Never mind :)
