### ISSUE TITLE
Setup TNQVM to take backend key for visitors

### ISSUE THREAD

**Issue by amccaskey** [ORNL-QCI/tnqvm#87]
Unless I've missed it and its already setup that way, can we add a few extra hetmap key checks to enable users to specify key 'backend' for a desired target tnqvm visitor? I'd like to see this so that it will more easily fit into our qcor and qcor-mlir-tool workflow - `qcor -qpu tnqvm:exatn-mps big_circuit.qasm` for instance.

**Comment by tnguyen-ornl** [comment]
This has been implemented, e.g. the syntax `tnqvm:exatn` is valid.
